apiVersion: v1
kind: PersistentVolume

metadata:
  name: exam-app-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Delete

  hostPath:
    path: /tmp/exam-app-data
